apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sebnsg3rz-python
  janus-idp.io/tekton: sebnsg3rz-python
  backstage.io/kubernetes-id: sebnsg3rz-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: sebnsg3rz-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
